spring:
    application:
        name: sirojungbotong
    profiles:
        active: local

    web:
        resources:
            static-locations: file:uploads/

    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    datasource:
        url: jdbc:mysql://localhost:3306/sirojungbotong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: sirojungbotong
        password: wkduddjq
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

    mail:
        host: smtp.gmail.com
        port: 587
        username: "sirojungbotong@gmail.com"
        password: "pnbtuvbtxpdsgjzr"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

jwt:
    secret: abcdefghijklmnopqrstuvwxyz123456
    access-token-expiration: 1800000
    refresh-token-expiration: 604800000

kakao:
    rest-api-key: "a2143200171ebfa11468f9e78f31fd5d"

business-verification:
    service-key: "4xZhDZS9Er1pzr8CQnQyurnbxomDN7cjIvVV1q9go7iDjPcVx%2BZ620hNKrS%2FogRhcBy%2B8PuuJ32rIs5RyfXfIw%3D%3D"
    api-url: "http://api.odcloud.kr/api/nts-businessman/v1/validate"

deepl:
    api-key: "763de7fc-bd3b-4792-866a-7b7ff3f19059:fx"

app:
    base-url: http://localhost:8080
    upload-path:
        flyer: backend/uploads/flyers
        store: backend/uploads/stores
        item: backend/uploads/items

