spring:
    application:
        name: sirojungbotong
    profiles:
        active: local

    web:
        resources:
            static-locations: file:uploads/

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

app:
    base-url: http://localhost:8080
    upload-path:
        flyer: backend/uploads/flyers
        store: backend/uploads/stores