spring:
    application:
        name: sirojungbotong
    profiles:
        active: local

    web:
        resources:
            static-locations: file:uploads/

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
